[tool.poetry]
name = "python-epub"
version = "0.1.0"
description = ""
authors = ["Arnaud <arnaudralec@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
epub2pdf = "^0.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
